//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataCenter.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LaserEngineDBEntities : DbContext
    {
        public LaserEngineDBEntities()
            : base("name=LaserEngineDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LibInfo> LibInfo { get; set; }
        public virtual DbSet<MachiningLib_Cutting> MachiningLib_Cutting { get; set; }
        public virtual DbSet<MachiningLib_EdgeCutting> MachiningLib_EdgeCutting { get; set; }
        public virtual DbSet<MachiningLib_Material> MachiningLib_Material { get; set; }
        public virtual DbSet<MachiningLib_Piercing> MachiningLib_Piercing { get; set; }
        public virtual DbSet<MachiningLib_SlopeControl> MachiningLib_SlopeControl { get; set; }
        public virtual DbSet<ManualInfo> ManualInfo { get; set; }
        public virtual DbSet<RootMachiningLib_Cutting> RootMachiningLib_Cutting { get; set; }
        public virtual DbSet<RootMachiningLib_EdgeCutting> RootMachiningLib_EdgeCutting { get; set; }
        public virtual DbSet<RootMachiningLib_Material> RootMachiningLib_Material { get; set; }
        public virtual DbSet<RootMachiningLib_Piercing> RootMachiningLib_Piercing { get; set; }
        public virtual DbSet<RootMachiningLib_SlopeControl> RootMachiningLib_SlopeControl { get; set; }
        public virtual DbSet<SparePart> SparePart { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserRole> UserRole { get; set; }
    }
}
