//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataCenter.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MachiningLib_SlopeControl
    {
        public string Id { get; set; }
        public short NO { get; set; }
        public string MachiningType { get; set; }
        public string MaterialType { get; set; }
        public double MaterialThickness { get; set; }
        public double FocalDistance { get; set; }
        public double FocalPosition { get; set; }
        public string CutterType { get; set; }
        public double CutterDiameter { get; set; }
        public short SlopeControl_PowerMin { get; set; }
        public short SlopeControl_PwrSpZr { get; set; }
        public short SlopeControl_FreqMin { get; set; }
        public short SlopeControl_FreqSpZr { get; set; }
        public short SlopeControl_DutyMin { get; set; }
        public short SlopeControl_DutySpZr { get; set; }
        public short SlopeControl_FeedRDec { get; set; }
        public double SlopeControl_FeedR { get; set; }
        public short SlopeControl_Reserve_1 { get; set; }
        public Nullable<short> SlopeControl_Reserve_2 { get; set; }
        public Nullable<short> SlopeControl_Reserve_3 { get; set; }
        public Nullable<short> SlopeControl_Reserve_4 { get; set; }
        public Nullable<short> SlopeControl_Reserve_5 { get; set; }
        public Nullable<short> SlopeControl_Reserve_6 { get; set; }
        public Nullable<short> SlopeControl_Reserve_7 { get; set; }
        public Nullable<short> SlopeControl_Reserve_8 { get; set; }
        public Nullable<short> SlopeControl_Reserve_9 { get; set; }
        public Nullable<short> SlopeControl_Reserve_10 { get; set; }
        public string SlopeControl_Reserve_Info_1 { get; set; }
        public string SlopeControl_Reserve_Info_2 { get; set; }
        public string SlopeControl_Reserve_Info_3 { get; set; }
    }
}
