//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataCenter.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MachiningLib_EdgeCutting
    {
        public string Id { get; set; }
        public short NO { get; set; }
        public string MachiningType { get; set; }
        public string MaterialType { get; set; }
        public double MaterialThickness { get; set; }
        public double FocalDistance { get; set; }
        public double FocalPosition { get; set; }
        public string CutterType { get; set; }
        public double CutterDiameter { get; set; }
        public double EdgeCutting_Angle { get; set; }
        public short EdgeCutting_Power { get; set; }
        public short EdgeCutting_Freq { get; set; }
        public short EdgeCutting_Duty { get; set; }
        public double EdgeCutting_Pier_T { get; set; }
        public double EdgeCutting_G_Press { get; set; }
        public short EdgeCutting_G_Kind { get; set; }
        public double EdgeCutting_R_Len { get; set; }
        public double EdgeCutting_R_Feed { get; set; }
        public short EdgeCutting_R_Freq { get; set; }
        public short EdgeCutting_R_Duty { get; set; }
        public double EdgeCutting_Gap { get; set; }
        public Nullable<short> EdgeCutting_Reserve_1 { get; set; }
        public Nullable<short> EdgeCutting_Reserve_2 { get; set; }
        public Nullable<short> EdgeCutting_Reserve_3 { get; set; }
        public Nullable<short> EdgeCutting_Reserve_4 { get; set; }
        public string EdgeCutting_Reserve_Info_1 { get; set; }
        public string EdgeCutting_Reserve_Info_2 { get; set; }
        public string EdgeCutting_Reserve_Info_3 { get; set; }
    }
}
